### ISSUE TITLE
Idea: Remove the "kill after steal" event by the shopkeeper.

### ISSUE THREAD

**Issue by twoco** [daid/LADXR#118]
I'm wondering if we can remove the event that starts after stealing and re-enter the shop. In this case, the shopkeeper is simply blind and never realizes that he has been robbed. (Does not increase the death counter for the photo or item. I see the name is already protected and not renamed to THIEF.)

Alternatively, we could just reduce the rubies instead of the hearts. At least that's a fairer form of punishment. The shopkeeper will take all rubies. Even if you have no rubies. After that he kicks you out the shop. idk

**Comment by daid** [comment]
Just don't steal? It's never logically required, and only one of the bingo goals can require it for the photo.

**Comment by twoco** [comment]
No, I want the shiny stuff - for free without consequences like in RL. ^^ The shopkeeper should be punished for killing. ...
To be honest nothing is required. It's just a suggestion for a new option. Just an idea. Feel free to close if you don't want it.

**Comment by twoco** [comment]
I don't want to farm rubies. But no problem. I found a solution. Just compare the savegame before and after your robbery. I found the address in a hex editor.

Offset: `0x44B`. The value `1` means you stole something and the shopkeeper will kill you the next time you enter the shop. Just change this value to `0` and everything is fine. Hehe

**Comment by daid** [comment]
> I don't want to farm rubies.
That's never needed. Shop items are only in logic once you can find enough rupees in chests.
