### ISSUE TITLE
reverse produce a spoiler

### ISSUE THREAD

**Issue by beanorx** [daid/LADXR#12]
not sure if mentioned elsewhere...and maybe this is more than one issue:  have a modified rom I want to spoil....  how do you go about this?   is the seed in the filename or on the file select screen?

**Comment by daid** [comment]
The seed is in the filename, and at the bottom of the file select screen (the top is the version of the generator used). If you use the same seed in the online generator with the same settings you should be able to generate a spoiler log.

You can also use the python code with `main.py --dump romfile.gbc` but that requires a bit more skill/knowledge.
