### ISSUE TITLE
Starting item Magic powder not refilable with the ghost when empty

### ISSUE THREAD

**Issue by Fishaphrodite** [daid/LADXR#32]
When the seed starts you with magic powder as your starting item, you get 10 uses out of it.
The magic powder in Link's Awakening doesn't have a "00" spot, instead it just disappears from your inventory once completely used up. The ghost will not be able to refill it then, which may result in being locked (the ghost will also not be there if there is no item in your inventory as a result of this specificity of magic powder).

this can be reproduced in a dungeon dive playthrough using : 
`python3 main.py zelda.gbc -s 0C58F1B866113CBF795FA1A3687EE683 --overworld dungeondive` 
(this seed is painful to get another item in, there are bombs in the color dungeon that can be accessed)

It happened to me in a run with regular overworld being set

`python3 main.py zelda.gbc -s 8C1795F8BC4231CD604A12C5F74728A7`

in which case I talked to the ghost after getting other refillable items, didn't get back the powder, but the mushroom did not respawn, upon grabbing one more magic powder under the witch's house pot, I then had 11 units of powder. The game may have given me back 10 units of powder when talking to the ghost, but without giving back the item to use said powder.

(This randomizer is very fun however, I just happened to have gotten magic powder as my first item in both randomized runs I tried)

**Comment by EpochFlame** [comment]
This seems to be fixed in current version, even with mushroom/witch set to not be randomized, as the magic powder does have a 00 counter.
