### ISSUE TITLE
"Super Weapons" makes turtle rock's elevated bomb dodongo fight (nearly) impossible

### ISSUE THREAD

**Issue by Xkeeper0** [daid/LADXR#40]
There are a few compounding issues that make the bomb snake fight in D8 _extremely_ difficult with super weapons on:

- You drop a new bomb every time you push the button, even if you pick up a bomb, so you are almost ensured to waste bombs you really need
- Throwing bombs anywhere other than to the furthest left edge is impossible; bombs are thrown with such force that they clip into walls anywhere else
- The miniboss is mostly random, meaning you have to wait potentially forever for the bosses to reach the top left corner of the arena

**Comment by daid** [comment]
![image](https://user-images.githubusercontent.com/964186/193444271-da714479-b3ff-4a55-8a03-90b43967766e.png)
This should fix it, only done when superweapons is on.
