### ISSUE TITLE
Stuck in a Logic Loop

### ISSUE THREAD

**Issue by FireTehVahu** [daid/LADXR#45]
I think I ran into a logic bug on link's awakening: 

So I need to enter the color dungeon but I can't because I currently have bow wow as my follower but I can't return him until Bottle Grotto is completed. I have found and used all but one key in the bottle grotto and it just so happens that I did not use the locked door to the path that leads to the boss so I checked the spoiler log and the key that I'm missing is located in the color dungeon.

No rooster run, led Marin to the Walrus and I have most items and keys. Aside from the Color Dungeon, Eagle's Tower, and Turtle Rock I have been pretty much everywhere in this seed.

[LADXR_9447B404110674866B04E5DE7D998A7D.txt](https://github.com/daid/LADXR/files/9446901/LADXR_9447B404110674866B04E5DE7D998A7D.txt)

EDIT: Apologies if this post is unnecessary. This may just be an unwinnable seed if the wrong choices are made.

**Comment by daid** [comment]
You should be able to enter the color dungeon with bowwow.

**Comment by daid** [comment]
Note that I really tried to patch away unsolvable paths by choices. The only exception right now is D3 (key cavern), if you waste keys on the keyblocks before you have enough keys, then there is a tiny potential to softlock.

So it's fine that you report this, rather have a few incorrect reports mixed in with correct ones then no reports at all.
