### ISSUE TITLE
[Logic]: Boots bonking against a wall to cross 1 tile gaps: inconsistencies

### ISSUE THREAD

**Issue by foxsouns** [daid/LADXR#65]
With only boots and bracelet, Heart Piece of Shame and mushroom are in Glitched, but Under Richard's House and the Mr. Write area checks are in Hell logic; but they all use the same tech?

**Comment by kbranch** [comment]
I think Dragon separated some things by difficulty or time invenstment even when the same tech is used. I'm not sure how that would apply here specifically, but there might be reasoning for it.

**Comment by foxsouns** [comment]
oh, i see. maybe it was because under richard's house boots-only is in a one wide hallway, and there is runup area for the others, thusly an easier trick? either way, i think ill close this, as it seems there isnt much wrong with it really.
