### ISSUE TITLE
[magpie]: d4 keyhole not properly handled

### ISSUE THREAD

**Issue by foxsouns** [daid/LADXR#87]
not exactly sure what's going on, but logic wants me to enter d4 without (proper) access to the keyhole.

my suspicions lie in [this bit of code](https://github.com/daid/LADXR/blob/master/logic/overworld.py#L357), though i dont know for sure.

found out some new tech, though! you can open d4 door from the taltal ledge using just boots and angler key, similar to what you can do with slime key. align yourself above keyhole, walk up slightly (while remaining clipped), and then hold a horizontal direction and down on the same frame. you should start the water softlock, but the location is where d4 ends up as, so you break out of it as long as you hit the key. should probably be hell logic for the 4-6 jesus bonks, i guess.

seed: `616D6F6E20677573`
settings: `LghsHTWRruEIl`
magpie state: [Magpie-state-2023-01-26T17_59_19.691Z.zip](https://github.com/daid/LADXR/files/10512088/Magpie-state-2023-01-26T17_59_19.691Z.zip)

**Comment by daid** [comment]
The logic there looks correct. The `d4_entrance` can only be reached by `lower_right_taltal` and requires both the key and `"ANGLER_KEYHOLE"` which is used to indicate access to the keyhole.

Any chance this is just a magpie bug where the keyhole isn't handled properly? @kbranch

**Comment by kbranch** [comment]
Yeah, looks like a Magpie issue. I thought there was some logic for when to add ANGLER_KEYHOLE, but it looks like it's just always on.

**Comment by foxsouns** [comment]
well, in that case, i guess there's nothing _i_ can do now about it. i do think i'm going to add `(that_taltal_ledge_or_whatever_its_called, AND(BOOTS, ANGLER_KEY)` to hell logic on my next PR.

**Comment by kbranch** [comment]
Fixed on Magpie's dev site now - I just populate logic with forced items now, so this and MEDICINE2, RAFT, etc. are all automatic.
